# This docker-compose file is to run tests on Docker.
version: "3.7"

services:
  test:
    build:
      context: .
      dockerfile: ./.testcontainer/Dockerfile
      args:
        - NAME_IMAGE=php:7.4.3-cli-alpine
    image: test/local:7.4.3
    volumes:
      - ./.git/:/app/.git
      - ./src:/app/src
      - ./tests:/app/tests
      - ./report:/app/report
