# =============================================================================
#  Docker container to test "initialize_package.php" functionability.
# =============================================================================

ARG COMPOSER='composer.json'

FROM php:alpine

USER root

RUN apk --no-cache add \
      git \
      bash

COPY . /app

WORKDIR /app

ENV COMPOSER="$COMPOSER"

RUN echo 'memory_limit = -1' >> "$(php -i | grep 'php.ini' | awk '{print $6}')/php.ini" && \
    /app/.devcontainer/install_composer.sh

ENTRYPOINT [ "/bin/sh", "/app/.devcontainer/entrypoint.test.initialize.sh" ]
